pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/vincentvgit/ansible-projet.git'
      }
    }

    stage('ansible job') {
      steps {
        withCredentials([azureServicePrincipal('azure')]) {
          sh 'ansible-playbook roles/* -i mon_inventaire.ini'
        }
      }   
  }
  }
}
