config
      copy:
        dest: "/root/.my.cnf"
        content: |
          [client]
          user=root
          password={{ root_password }}
      mode: 0400

    - name: Allow external MySQL connections (1/2)
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^skip-external-locking'
        line: "# skip-external-locking"
      notify: Restart mysql

    - name: Allow external MySQL connections (2/2)
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: "# bind-address"
      notify: Restart mysql

    - name: Upload SQL table config
      template:
        src: "table.sql.j2"
        dest: "/tmp/table.sql"

    - name: Add SQL table to database
      mysql_db:
        name: "{{ mysql_dbname }}"
        state: import
        login_user: root
        login_password: '{{ root_password }}'
        target: /tmp/table.sql

    - name: "Create {{ mysql_user }} with all {{ mysql_dbname }} privileges"
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "{{ mysql_dbname }}.*:ALL"
        host: "{{ webserver_host }}"
        state: present
        login_user: root
        login_password: '{{ root_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted
