---
- name: WEB SERVER
  hosts: websrv
  become: true
  vars_files:
    - roles/apache.yaml

  roles:
    - role: apache

- name: DATABASE SERVER
  hosts: mysql
  become: true
  vars_files:
    - roles/mysql.yaml

  roles:
    - role: mysql
